# Generated by Django 4.2.13 on 2025-07-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kylinApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinformationmanagement',
            name='remarks',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
