# Generated by Django 5.2.3 on 2025-08-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kylinApp', '0003_add_server_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='日志标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='日志描述')),
                ('type', models.CharField(choices=[('system', '系统日志'), ('application', '应用日志'), ('security', '安全日志'), ('performance', '性能日志'), ('other', '其他')], default='system', max_length=50, verbose_name='日志类型')),
                ('file_path', models.CharField(max_length=255, verbose_name='文件路径')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('status', models.CharField(choices=[('success', '成功'), ('pending', '处理中'), ('error', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'log_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='monitoringserverinformation',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='备注'),
        ),
    ]
