# Generated by Django 4.2.13 on 2025-08-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kylinApp', '0004_logrecord_alter_monitoringserverinformation_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
