# Generated by Django 4.2.13 on 2025-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kylinApp', '0005_alter_usermodels_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='file_blob',
            field=models.BinaryField(blank=True, null=True, verbose_name='文件内容'),
        ),
        migrations.AddField(
            model_name='logrecord',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径'),
        ),
    ]
